pipeline {
    agent any

    environment {
        MAVEN_HOME = "/usr/share/maven"
        PATH = "$PATH:$MAVEN_HOME/bin"
        DOCKER_IMAGE = "shaikirfan273/scientific-calculator"
        SERVER_IP = "172.16.231.25"
        SSH_KEY_PATH = "/var/lib/jenkins/.ssh/id_rsa"
    }

    stages {
        stage('Setup Permissions') {
            steps {
                script {
                    sh '''
                    echo "Granting permissions to Jenkins user.."
                    sudo usermod -aG docker jenkins
                    sudo chown -R jenkins:jenkins /var/lib/jenkins/.ssh
                    sudo chmod 700 /var/lib/jenkins/.ssh
                    '''
                }
            }
        }

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/SHAIK-MOHAMMAD-IRFAN27/SPE_Calculator.git' 
            }
        }

        stage('Build') {
            steps {
                dir('ScientificCalculator') {  
                    sh 'mvn clean package'
                }
            }
        }

        stage('Test') {
            steps {
                dir('ScientificCalculator') {
                    sh 'mvn test'
                }
            }
        }

        stage('Containerize Application') {
            steps {
                dir('ScientificCalculator') {
                    sh 'sudo docker build -t ${DOCKER_IMAGE} .'
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: '28019f59-3f30-48dc-aa75-2c0fd46caa2c',
                                                  usernameVariable: 'DOCKER_USER',
                                                  passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                    echo "Log into Docker Hub"
                    echo "${DOCKER_PASS}" | sudo docker login -u "${DOCKER_USER}" --password-stdin
                    sudo docker push ${DOCKER_IMAGE}
                    '''
                }
            }
        }

        stage('Run Ansible Deployment') {
            steps {
                dir('ScientificCalculator') {
                script {
                    sh '''
                    echo "Creating Ansible hosts.ini file..."

                    echo "Running Ansible Playbook.."
                    ansible-playbook -i hosts.ini deploy.yml
                    '''
                }
                }
            }
        }
    }  

    post {
        success {
            echo "Pipeline executed successfully! The Scientific Calculator is deployed."
        }
        failure {
            echo "Pipeline failed! Check the logs for errors."
        }
    }
}

